"""Initial schema: rate cards, quotes, discrepancies, idempotency.

Revision ID: 0001
Revises:
Create Date: 2026-09-02

Hand-written rather than autogenerated, for two reasons autogenerate cannot
express:

- ``payload`` is a **variant** type -- JSONB on Postgres, plain JSON elsewhere.
  Autogenerate renders whichever dialect it was pointed at, which would make
  the migration unrunnable on the other one.
- The two partial indexes need ``postgresql_where`` *and* ``sqlite_where``. On
  SQLite a bare unique index over ``list_id`` would forbid keeping superseded
  rate card versions, and CLAUDE.md requires keeping them.
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects.postgresql import JSONB

revision: str = "0001"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None

#: Mirrors ``app.models.db.JsonColumn``. Repeated here rather than imported: a
#: migration is a snapshot of the schema at a point in time, and must not shift
#: when the models change.
JsonColumn = sa.JSON().with_variant(JSONB(), "postgresql")


def upgrade() -> None:
    # Rows here are never updated in place and never deleted. A price change
    # publishes a new version; the old one stays readable so a quote that
    # recorded version 1 can still be explained after version 2 exists.
    op.create_table(
        "rate_cards",
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("list_id", sa.String(length=32), nullable=False),
        sa.Column("payload", JsonColumn, nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column(
            "published_at",
            sa.DateTime(timezone=True),
            server_default=sa.func.now(),
            nullable=False,
        ),
        sa.Column("published_by", sa.String(length=64), nullable=True),
        sa.PrimaryKeyConstraint("version"),
    )
    # One active card per list, enforced by the database rather than by
    # application discipline: two active fair cards would price two devices
    # differently on the same day.
    op.create_index(
        "ix_rate_cards_active",
        "rate_cards",
        ["list_id"],
        unique=True,
        postgresql_where=sa.text("is_active"),
        sqlite_where=sa.text("is_active"),
    )

    # ``id`` is the device's own UUID v4, not one the server invents. Two
    # part-timers offline at one fair must never collide, and it is what makes
    # the push idempotent: a retry carries the same id.
    op.create_table(
        "quotes",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("rate_card_version", sa.Integer(), nullable=False),
        sa.Column("tier", sa.String(length=16), nullable=False),
        sa.Column("language", sa.String(length=4), nullable=False),
        sa.Column("customer_name", sa.String(length=120), nullable=True),
        sa.Column("customer_phone", sa.String(length=40), nullable=True),
        sa.Column("delivery_zone_id", sa.String(length=64), nullable=True),
        # Both figures, side by side. Section 9.4 compares them; neither
        # overwrites the other.
        sa.Column("device_total_sen", sa.BigInteger(), nullable=True),
        sa.Column("server_total_sen", sa.BigInteger(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column(
            "received_at",
            sa.DateTime(timezone=True),
            server_default=sa.func.now(),
            nullable=False,
        ),
        sa.Column("device_id", sa.String(length=36), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("ix_quotes_received", "quotes", ["received_at"])

    # Stores what was *entered*, never what was computed, so the server can
    # price the line independently. Money is integer sen, lengths integer
    # tenths of a millimetre.
    op.create_table(
        "quote_lines",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("quote_id", sa.String(length=36), nullable=False),
        sa.Column("sort_order", sa.Integer(), nullable=False),
        sa.Column("room", sa.String(length=80), nullable=False),
        sa.Column("variant", sa.String(length=64), nullable=False),
        sa.Column("material_key", sa.String(length=64), nullable=True),
        sa.Column("layer", sa.String(length=16), nullable=False),
        sa.Column("parent_line_id", sa.String(length=36), nullable=True),
        sa.Column("width_tmm", sa.Integer(), nullable=False),
        sa.Column("height_tmm", sa.Integer(), nullable=True),
        sa.Column("raw_width", sa.String(length=32), nullable=False),
        sa.Column("raw_height", sa.String(length=32), nullable=False),
        sa.Column("quantity", sa.Integer(), nullable=False),
        sa.Column("device_total_sen", sa.BigInteger(), nullable=True),
        sa.Column("server_total_sen", sa.BigInteger(), nullable=True),
        sa.ForeignKeyConstraint(["quote_id"], ["quotes.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("ix_quote_lines_quote", "quote_lines", ["quote_id", "sort_order"])

    # APPEND ONLY. A mismatch means the Dart and Python engines have drifted,
    # and this table is how that is found before a customer notices.
    op.create_table(
        "pricing_discrepancies",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("quote_id", sa.String(length=36), nullable=False),
        sa.Column("line_id", sa.String(length=36), nullable=False),
        sa.Column("rate_card_version", sa.Integer(), nullable=False),
        sa.Column("device_total_sen", sa.BigInteger(), nullable=False),
        sa.Column("server_total_sen", sa.BigInteger(), nullable=False),
        sa.Column("detail", sa.Text(), nullable=True),
        sa.Column(
            "at",
            sa.DateTime(timezone=True),
            server_default=sa.func.now(),
            nullable=False,
        ),
        sa.Column("reviewed_at", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    # Partial: the review queue is the unreviewed rows, and that set stays
    # small while the table grows forever.
    op.create_index(
        "ix_discrepancies_unreviewed",
        "pricing_discrepancies",
        ["at"],
        postgresql_where=sa.text("reviewed_at IS NULL"),
        sqlite_where=sa.text("reviewed_at IS NULL"),
    )

    # Proof that a push has already been applied. A fair's connection drops
    # mid-request constantly; this table is what makes the retry harmless.
    op.create_table(
        "idempotency",
        sa.Column("key", sa.String(length=80), nullable=False),
        sa.Column("entity_type", sa.String(length=32), nullable=False),
        sa.Column("entity_id", sa.String(length=36), nullable=False),
        sa.Column(
            "at",
            sa.DateTime(timezone=True),
            server_default=sa.func.now(),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("key"),
        sa.UniqueConstraint("entity_type", "entity_id", name="uq_idempotency_entity"),
    )


def downgrade() -> None:
    op.drop_table("idempotency")
    op.drop_index("ix_discrepancies_unreviewed", table_name="pricing_discrepancies")
    op.drop_table("pricing_discrepancies")
    op.drop_index("ix_quote_lines_quote", table_name="quote_lines")
    op.drop_table("quote_lines")
    op.drop_index("ix_quotes_received", table_name="quotes")
    op.drop_table("quotes")
    op.drop_index("ix_rate_cards_active", table_name="rate_cards")
    op.drop_table("rate_cards")
